name: Dependency Review
on: 
  workflow_dispatch:
permissions:
  contents: read
jobs:
  dependency-review:
    name: Dependency review
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@1c9a424cbc6f5bc5724f6875ea791bf08e1bfb40
        with:
          fail-on-severity: low
          license-check: false
